### PR TITLE
Fixed issue with config.json file not being found and issue where upstreamPort wasn't being honored

### PR DESCRIPTION
**Pull request by ahmednuaman**
I've noticed that you're not running the unit tests on a CI, do you want me to set up Travis for you?

### CODE REVIEW

**Comment by jdpaton** [comment]
Thanks!, any reason to prefer `JSON.parse(Fs.readFileSync())` for JSON files? It looks like it does the same thing [here](https://github.com/joyent/node/blob/588d885e81dec667920383ac7246daceeb7f99fd/lib/module.js#L469).

I'm looking into the Travis CI setup now.

**Comment by jdpaton** [comment]
Travis CI is setup: https://travis-ci.org/ActiveState/npm-lazy-mirror

**Comment by ahmednuaman** [comment]
So I found that when I used the `-C` option I received this error:

```
module.js:340
    throw err;
    ^
Error: Cannot find module 'config.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/anu01/bin/node-v0.10.26-darwin-x64/lib/node_modules/npm-lazy-mirror/lib/config.js:56:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by ahmednuaman** [comment]
So when I saw it was using `require`, I thought I'd try and use FS and parse the JSON file instead.

**Comment by ahmednuaman** [comment]
I've also added the config option `upstream_db_path`, this is to deal with a DB path that may not be `/`, eg for me it's `/registry/_design/app/_rewrite` and I also fixed the issue where the port and DB path configs hadn't been added to the upstream proxy function.

**Comment by ahmednuaman** [comment]
All tidied up now, thanks for the patience :beer:

**Comment by jdpaton** [comment]
Thanks!

**Pull request merged**
